#!/bin/bash
#
# Any Linux specific config goes here.

# bash-completion
if [[ $PS1 && -f /usr/share/bash-completion/bash_completion ]]; then
  . /usr/share/bash-completion/bash_completion
else
  echo "bash-completion is not installed, not everything may work as expected!"
fi

# Solarized dircolors
eval $(dircolors $DOTFILES/lib/dircolors-solarized/dircolors.ansi-universal)
alias ls='ls -F --color'

# Start a ssh-agent session if there isn't already one running and save its output.
#
# If there is already a session running, load its cached output to set the
# required environment variables for it to work.
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent > ~/.ssh-agent-cache
fi
if [[ "$SSH_AGENT_PID" == "" ]]; then
    eval "$(<~/.ssh-agent-cache)"
fi
