#!/bin/bash

export EDITOR="e"

alias c="wl-copy"
alias p="wl-paste"

export PATH="$HOME/.local/bin:$PATH"

# "user@host:cwd" as window title
case ${TERM} in

  xterm*|rxvt*|Eterm|alacritty|aterm|kterm|gnome*)
     PROMPT_COMMAND=${PROMPT_COMMAND:+$PROMPT_COMMAND; }'printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"'

    ;;
  screen*)
    PROMPT_COMMAND=${PROMPT_COMMAND:+$PROMPT_COMMAND; }'printf "\033_%s@%s:%s\033\\" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"'
    ;;
esac

